title = "Strongbread"
baseURL = "https://strongbread.com"
languageCode = "en-us"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Damian’s Daily Bread"
weight = 1
contentDir = "content"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Damian’s Daily Bread, unsorted"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-washed-yellow"
recent_posts_number = 3

[[params.ananke_socials]]
name = "Hevy"
url = "https://hevy.com/user/loafd"